from cloudforet.plugin.manager.base import ResourceManager
from cloudforet.plugin.manager.recommender.iam_management_manager import IAMManagementRecommendationManager
from cloudforet.plugin.manager.recommender.all_recommendations_manager import AllRecommendationsManager
